#!/usr/bin/python3 -u

import sys
import socket
import psutil
import pymunge

def get_cgroup(pid):
  with open(f"/proc/{pid}/cgroup", 'r') as f:  
    for line in f.readlines():
      if 'memory' in line:
        return line.split(':')[2].strip()
try:
  connections = []
  for proc in psutil.process_iter():
    try:
      for c in proc.connections('tcp'):
        if c.status == 'ESTABLISHED' and c.raddr[1] == 22:
          connections.append(f"{c.laddr[0]}:{c.laddr[1]} {c.raddr[0]}:{c.raddr[1]} {proc.username()} {get_cgroup(proc.pid)}")
    except psutil.NoSuchProcess:
      pass


  ctx = pymunge.MungeContext()
  ctx.uid_restriction = 0
  sys.stdout.buffer.write(ctx.encode("\n".join(connections).encode('utf-8')))

except Exception as e:
  print(e, file=sys.stderr)
