#!/usr/bin/python36

import os
import sys
import time
import signal
import socket
import psutil
import pymunge
import xml.etree.ElementTree as ElementTree
from functools import reduce
from syslog import openlog, syslog, LOG_AUTHPRIV

JOBS_PATH = '/var/spool/torque/mom_priv/jobs/'


def timeout(*args):
  syslog(f"Timed out.")
  os._exit(0)

def place_pid(pid, cgroup):
  syslog(f"Placing pid {pid} in cgroup {cgroup}")

  try:
    for subsys in ['memory', 'cpuset', 'devices', 'cpuacct']:
      with open(f"/sys/fs/cgroup/{subsys}{cgroup}/tasks", 'a') as f:
        f.write(f"{pid}\n")
  except Exception as e:
    syslog("Failed to place in cgroup!")
    syslog(str(e))

  os._exit(0)

def scan_jobs(user):
  jobs = {}
  for file in os.listdir(JOBS_PATH):
    if not file.endswith("JB"):
      continue

    root = ElementTree.parse(os.path.join(JOBS_PATH, file)).getroot()
    jobid = root.find("./jobid").text
    euser = root.find("./attributes/euser").text
    start = root.find("./attributes/start_time").text
    if user == euser:
      jobs[jobid] = int(start)
  return jobs

def match_remote_cgroup(host, local, remote):
  try:
    s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    s.connect( (host, 411) )
  except:
    syslog("Failed to connect to remote torque_adopt..")
    return

  try:
    payload, uid, _, _ = pymunge.decode(s.recv(65536))
  except:
    syslog("Failed to decrypt remote torque_adopt payload..")
    return

  for line in payload.decode('utf-8').splitlines():
    r_local, r_remote, r_user, r_cgroup = line.split()
    if user == r_user and r_remote == local and r_local == remote:
      if r_cgroup.startswith("/torque"):
        syslog(f"Found matching remote torque cgroup: {r_cgroup}")
        place_pid(parent.pid, r_cgroup)

def place_in_recent_job(user):
  # jobs is a map of { "<jobid>": <start time> } for user
  jobs = scan_jobs(user)
  if jobs:
    # reduce the jobs list to the job that most recently started
    job = reduce(lambda x, y: x if jobs[x] > jobs [y] else y, jobs)
    if job:
      place_pid(parent.pid, f"/torque/{job}")

try:
  openlog('torque_adopt', facility=LOG_AUTHPRIV)
  signal.signal(signal.SIGALRM, timeout)
  signal.alarm(5)

  parent = psutil.Process(os.getppid())

  # reopen syslog with the proper sshd prefix
  # keep the above open for exception logging of things that happen before we get the parent pid
  openlog(f"sshd[{parent.pid}]: torque_adopt", facility=LOG_AUTHPRIV)

  user = os.environ['PAM_USER']

  if user == "root":
    os._exit(0)  
  if os.environ['PAM_SERVICE'] != "sshd":
    os._exit(0)
  if os.environ['PAM_TYPE'] != "open_session":
    os._exit(0)
 

  # Our parent is a root sshd forked to just handle this session
  # It _should_ only have one connection, the one for this session
  connection = parent.connections()[0] 
  local_ip, local_port    = connection.laddr
  remote_ip, remote_port = connection.raddr
  local  = f"{local_ip}:{local_port}"
  remote = f"{remote_ip}:{remote_port}"

  try:
    match_remote_cgroup(remote_ip, local, remote)
  except:
    pass
  
  syslog("Failed to match remote cgroup..")
    
  try:
    place_in_recent_job(user)
  except:
    pass
  
  syslog("Failed to place in user's most recent job..")
  place_pid(parent.pid, "/")

except Exception as e:
  syslog(str(e))
  if parent:
    syslog('An exception occured, placing in root.')
    place_pid(parent.pid, '/')
